[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle SPA routing - but preserve direct file access
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/work"
  to = "/work.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/vibes"
  to = "/vibes.html"
  status = 200

[[redirects]]
  from = "/journalism"
  to = "/journalism.html"
  status = 200

[[redirects]]
  from = "/marketing"
  to = "/marketing.html"
  status = 200

[[redirects]]
  from = "/texture"
  to = "/texture.html"
  status = 200

[[redirects]]
  from = "/serenity"
  to = "/serenity.html"
  status = 200

[[redirects]]
  from = "/spirit"
  to = "/spirit.html"
  status = 200

[[redirects]]
  from = "/adventure"
  to = "/adventure.html"
  status = 200

[[redirects]]
  from = "/commencement"
  to = "/commencement.html"
  status = 200

[[redirects]]
  from = "/film"
  to = "/film.html"
  status = 200

# Enable asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable font caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"